# Generated by Django 4.2 on 2023-05-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Zip_code',
            new_name='zip_code',
        ),
    ]
